Repository coopcycle/coopcycle-app, pull requests merged in 2025-09, with the labels that each got.

#2031 [PERTE-491] Put back task status icon
  src/components/TaskList.tsx
  src/components/TaskListItem.tsx
  src/components/TaskStatusIcon.tsx
Labels: Courier Interface, Dispatch Interface, Cooperative: Transversal Concepts, UX/UI

#2042 [PERTE-451] Avoid task updated notification modal for admins and dispatchers
  src/redux/App/selectors.ts
Labels: enhancement, Dispatch Interface, Cooperative: Transversal Concepts, Notifications

#2036 [PERTE-459] Apply design for long-tap actions for task list item
  src/components/Icon.tsx
  src/components/IconText.tsx
  src/components/ItemTouchable.tsx
  src/components/OrderInfo.tsx
  src/components/TaskInfo.tsx
  src/components/TaskList.tsx
  src/components/TaskListItem.tsx
  src/components/TaskPriorityStatus.tsx
  src/components/TaskStatusIcon.tsx
  src/components/TaskTagsList.tsx
  src/components/TaskTypeIcon.tsx
  src/navigation/courier/Settings.tsx
  src/navigation/dispatch/components/BulkEditTasksFloatingButton.tsx
  src/navigation/dispatch/components/GroupedTasks.tsx
  src/navigation/order/utils.ts
  src/navigation/task/styles/common.ts
  src/shared/src/utils.js
  src/types/task.ts
Labels: enhancement, Dispatch Interface, Cooperative: Transversal Concepts, UX/UI
